name: dbtvault_msfabric_demo
profile: dbtvault_msfabric_demo
version: '1.0.0'
config-version: 2

vars:
  load_date: '2024-02-01'
  # tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  dbtvault_msfabric_demo:
    raw_stage:
      materialized: table
      tags: ['raw']
    stage:
      materialized: view
      tags: ['stage']
      enabled: true

    raw_vault:
      tags: ['raw_vault']
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'

macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target    

clean-targets:
    - "target"
    - "dbt_packages"

dispatch:
  - macro_namespace:  dbtvault-msfabric-demo
    search_order: ['dbtvault-msfabric-demo', 'automate_dv']